# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import calculator_pb2 as calculator__pb2


class CaculatorStub(object):
  """Calculator is a dummy server that tests the implementation of gRPC server in Python.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Add = channel.unary_unary(
        '/Caculator/Add',
        request_serializer=calculator__pb2.Input.SerializeToString,
        response_deserializer=calculator__pb2.Output.FromString,
        )


class CaculatorServicer(object):
  """Calculator is a dummy server that tests the implementation of gRPC server in Python.
  """

  def Add(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CaculatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Add': grpc.unary_unary_rpc_method_handler(
          servicer.Add,
          request_deserializer=calculator__pb2.Input.FromString,
          response_serializer=calculator__pb2.Output.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Caculator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
