# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommendation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='recommendation.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('Z\007protogo'),
  serialized_pb=_b('\n\x14recommendation.proto\"&\n\x10RecommendRequest\x12\x12\n\nuser_email\x18\x01 \x01(\t\"M\n\x05Movie\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07imdb_id\x18\x03 \x01(\t\x12\x18\n\x10predicted_rating\x18\x04 \x01(\x01\"+\n\x11RecommendResponse\x12\x16\n\x06movies\x18\x01 \x03(\x0b\x32\x06.Movie\"#\n\rUpdateRequest\x12\x12\n\nuser_email\x18\x01 \x01(\t\"\"\n\x0eUpdateResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x32y\n\x0eRecommendation\x12.\n\x05\x46\x65tch\x12\x11.RecommendRequest\x1a\x12.RecommendResponse\x12\x37\n\x14UpdateUserPreference\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponseB\tZ\x07protogob\x06proto3')
)




_RECOMMENDREQUEST = _descriptor.Descriptor(
  name='RecommendRequest',
  full_name='RecommendRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_email', full_name='RecommendRequest.user_email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=62,
)


_MOVIE = _descriptor.Descriptor(
  name='Movie',
  full_name='Movie',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Movie.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='Movie.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imdb_id', full_name='Movie.imdb_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='predicted_rating', full_name='Movie.predicted_rating', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=141,
)


_RECOMMENDRESPONSE = _descriptor.Descriptor(
  name='RecommendResponse',
  full_name='RecommendResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='movies', full_name='RecommendResponse.movies', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=186,
)


_UPDATEREQUEST = _descriptor.Descriptor(
  name='UpdateRequest',
  full_name='UpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_email', full_name='UpdateRequest.user_email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=223,
)


_UPDATERESPONSE = _descriptor.Descriptor(
  name='UpdateResponse',
  full_name='UpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accepted', full_name='UpdateResponse.accepted', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=259,
)

_RECOMMENDRESPONSE.fields_by_name['movies'].message_type = _MOVIE
DESCRIPTOR.message_types_by_name['RecommendRequest'] = _RECOMMENDREQUEST
DESCRIPTOR.message_types_by_name['Movie'] = _MOVIE
DESCRIPTOR.message_types_by_name['RecommendResponse'] = _RECOMMENDRESPONSE
DESCRIPTOR.message_types_by_name['UpdateRequest'] = _UPDATEREQUEST
DESCRIPTOR.message_types_by_name['UpdateResponse'] = _UPDATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecommendRequest = _reflection.GeneratedProtocolMessageType('RecommendRequest', (_message.Message,), dict(
  DESCRIPTOR = _RECOMMENDREQUEST,
  __module__ = 'recommendation_pb2'
  # @@protoc_insertion_point(class_scope:RecommendRequest)
  ))
_sym_db.RegisterMessage(RecommendRequest)

Movie = _reflection.GeneratedProtocolMessageType('Movie', (_message.Message,), dict(
  DESCRIPTOR = _MOVIE,
  __module__ = 'recommendation_pb2'
  # @@protoc_insertion_point(class_scope:Movie)
  ))
_sym_db.RegisterMessage(Movie)

RecommendResponse = _reflection.GeneratedProtocolMessageType('RecommendResponse', (_message.Message,), dict(
  DESCRIPTOR = _RECOMMENDRESPONSE,
  __module__ = 'recommendation_pb2'
  # @@protoc_insertion_point(class_scope:RecommendResponse)
  ))
_sym_db.RegisterMessage(RecommendResponse)

UpdateRequest = _reflection.GeneratedProtocolMessageType('UpdateRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEREQUEST,
  __module__ = 'recommendation_pb2'
  # @@protoc_insertion_point(class_scope:UpdateRequest)
  ))
_sym_db.RegisterMessage(UpdateRequest)

UpdateResponse = _reflection.GeneratedProtocolMessageType('UpdateResponse', (_message.Message,), dict(
  DESCRIPTOR = _UPDATERESPONSE,
  __module__ = 'recommendation_pb2'
  # @@protoc_insertion_point(class_scope:UpdateResponse)
  ))
_sym_db.RegisterMessage(UpdateResponse)


DESCRIPTOR._options = None

_RECOMMENDATION = _descriptor.ServiceDescriptor(
  name='Recommendation',
  full_name='Recommendation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=261,
  serialized_end=382,
  methods=[
  _descriptor.MethodDescriptor(
    name='Fetch',
    full_name='Recommendation.Fetch',
    index=0,
    containing_service=None,
    input_type=_RECOMMENDREQUEST,
    output_type=_RECOMMENDRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateUserPreference',
    full_name='Recommendation.UpdateUserPreference',
    index=1,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=_UPDATERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECOMMENDATION)

DESCRIPTOR.services_by_name['Recommendation'] = _RECOMMENDATION

# @@protoc_insertion_point(module_scope)
