# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import recommendation_pb2 as recommendation__pb2


class RecommendationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Fetch = channel.unary_unary(
        '/Recommendation/Fetch',
        request_serializer=recommendation__pb2.RecommendRequest.SerializeToString,
        response_deserializer=recommendation__pb2.RecommendResponse.FromString,
        )
    self.UpdateUserPreference = channel.unary_unary(
        '/Recommendation/UpdateUserPreference',
        request_serializer=recommendation__pb2.UpdateRequest.SerializeToString,
        response_deserializer=recommendation__pb2.UpdateResponse.FromString,
        )


class RecommendationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Fetch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateUserPreference(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RecommendationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Fetch': grpc.unary_unary_rpc_method_handler(
          servicer.Fetch,
          request_deserializer=recommendation__pb2.RecommendRequest.FromString,
          response_serializer=recommendation__pb2.RecommendResponse.SerializeToString,
      ),
      'UpdateUserPreference': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUserPreference,
          request_deserializer=recommendation__pb2.UpdateRequest.FromString,
          response_serializer=recommendation__pb2.UpdateResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Recommendation', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
