version: '3'
services:
  frontend:
    container_name: "api"
    image: api
    ports:
      - "8000:8000"
  backend:
    container_name: "recommender"
    image: recommender
    ports:
      - "8080:8080"