version: '3'
services:
  frontend:
    build: ./api
    image: api
    container_name: api
    ports:
      - 8080:8080
    links:
      - backend
  backend:
    build: ./recommender
    image: recommender
    container_name: recommender
    ports:
      - 8081:8081