[grpc]
port = "8081"

[database]
name = "popcorn"
user = "popcorn"
password = "popcorn"
hostname = "localhost"
port = 5432
ssl_mode = "disable"

[data]
dir = "./datasets/100k"

[personalized_training]
num_steps = 1000
feature_dim = 10
regularization = 0.05
learning_rate = 2e-5
