[data]
dir = "../datasets/100k"

[data.filter]
min_ratings_per_user = 50

[database]
name = "popcorn"
user = "cfeng"
password = "cfeng"
hostname = "localhost"
port = 5432
ssl_mode = "disable"

[personalized_training]
num_steps = 1000
feature_dim = 10
regularization = 5e-2
learning_rate = 1e-3

[model_training]
num_steps = 1000
epoch_size = 50
feature_dim = 10
regularization = 5e-2
learning_rate = 2e-5