[grpc]
port = "8081"

[database]
name = "popcorn"
user = "popcorn"
password = "popcorn"
hostname = "localhost"
port = 5432
ssl_mode = "disable"

[ml]
dataset_dir = "./datasets/27m"
steps = 10
epoch = 1
regularization = 0.05
learning_rate = 0.00001
feature_dim = 10
min_ratings_per_user = 50